language: node_js
node_js:
  - 13

services:
  - docker

# Build image and tag
script:
  - docker --version

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed abobo/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user abobo/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend abobo/udagram-frontend:v1

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy abobo/udagram-reverseproxy:v1

# push images to docker hub
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abobo/udagram-api-feed:v1
  - docker push abobo/udagram-api-user:v1
  - docker push abobo/udagram-frontend:v1
  - docker push abobo/udagram-reverseproxy:v1
