apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: udagram-api-user
          image: abobo/udagram-api-user:v1
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: postgres_password
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: postgres_username
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: url
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: aws_region
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: aws_profile
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: jwt_secret
          ports:
            - containerPort: 8080
